[platformio]
default_envs = float, surface

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = picosdk
monitor_speed = 115200
monitor_filters = colorize, send_on_enter
monitor_echo = yes
build_type = debug
lib_ldf_mode = deep
extra_scripts = 
    post:generate_bin.py
    tools/dual_upload.py
build_unflags = -D PICO_STDIO_UART
lib_deps =
build_flags =
    -O2
    -Wl,-u,_printf_float
    -D PICO_STDIO_UART=0
    -D PICO_STDIO_DEFAULT_CRLF=0
    -Wl,-u,_scanf_float
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    -I lib/MS5837
    -I lib/BN085
    -I lib/fsm
    -I lib/RadioLib
    -I lib/reflash
    -I lib/surface_fsm
    -I lib/console
    -I lib/data_logger
    -I lib/config
    -I lib/actuator
    -I lib/comms
    -I lib/pid
    -I lib/depth_pid
    -I lib/storage
    -I lib/neopixel
    -I lib/bsdiff

[env:bootloader]
build_flags =
    ${env.build_flags}
    -D TARGET_BOOTLOADER
    -D PICO_STDIO_USB
    -D PICO_USB=1
build_src_filter = -<*> +<bootloader_main.c>
upload_port = COM9
monitor_port = COM9

[env:float]
board_build.ldscript = $PROJECT_DIR/linker_scripts/app_memmap.ld
build_flags =
    ${env.build_flags}
    -D TARGET_FLOAT
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
build_src_filter = -<*> +<float_main.c>
upload_port = COM13
monitor_port = COM13

[env:float_hil]
board_build.ldscript = linker_scripts/app_memmap.ld
build_flags =
    ${env.build_flags}
    -D TARGET_FLOAT
    -D HIL_MODE
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
build_src_filter = -<*> +<float_main.c>
upload_port = COM3
monitor_port = COM3


[env:surface]
board = pico
build_flags = 
    ${env.build_flags}
    -D TARGET_SURFACE
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
build_src_filter = -<*> +<surface_main.c>
upload_port = COM18
monitor_port = COM18

[env:diag_float]
board = adafruit_feather
build_flags =
    ${env.build_flags}
    -D TARGET_FLOAT
    -D NODE_PING
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
build_src_filter = -<*> +<radio_diagnostic.c>
upload_port = COM13
monitor_port = COM13

[env:diag_surface]
board = pico
build_flags = 
    ${env.build_flags}
    #-D NODE_PING
    -D TARGET_SURFACE
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
build_src_filter = -<*> +<radio_diagnostic.c>
upload_port = COM18
monitor_port = COM18


[env:test_print]
build_flags =
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
build_src_filter = -<*> +<test_print.c>
upload_port = COM13
monitor_port = COM13