[platformio]
default_envs = float, surface

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = picosdk
monitor_speed = 115200
monitor_filters = colorize, send_on_enter
monitor_echo = yes
build_type = debug
build_unflags = -D PICO_STDIO_UART
build_flags =
    -O2
    -D PICO_STDIO_USB
    -D PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE=1
    -D PICO_USB=1
    -Wl,-u,_printf_float
    -D PICO_STDIO_UART=0
    -Wl,-u,_scanf_float
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    -I lib/MS5837
    -I lib/BN085
    -I lib/fsm
    -I lib/RadioLib
    -I lib/reflash
    -I lib/surface_fsm
    -I lib/console
    -I lib/data_logger
    -I lib/config
    -I lib/actuator
    -I lib/comms
    -I lib/pid
    -I lib/depth_pid
    -I lib/storage
    -I lib/neopixel

[env:float]
build_flags =
    ${env.build_flags}
    -D TARGET_FLOAT
build_src_filter = -<*> +<float_main.c>
upload_port = COM15
monitor_port = COM15

[env:surface]
build_flags = 
    ${env.build_flags}
    -D TARGET_SURFACE
build_src_filter = -<*> +<surface_main.c>
upload_port = COM9
monitor_port = COM9