[env:adafruit_feather]
# We use the community fork that allows Pico SDK on non-Pico boards
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = picosdk

# Optimization and Serial Monitor
monitor_speed = 115200
build_type = debug
build_unflags = -D PICO_STDIO_UART
build_flags =
    -O2
    -D PICO_STDIO_USB
    -D PICO_USB=1
    -Wl,-u,_printf_float
    -D PICO_STDIO_UART=0
    -Wl,-u,_scanf_float
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    ; Add include paths for your libraries so main.c can find the .h files
    -I lib/MS5837
    -I lib/BN085
    -I lib/fsm
    -I lib/RadioLib
    -I lib/reflash
    -I lib/surface_fsm
    -I lib/surface_link
    -I lib/data_logger

# Just like your other project, ensure all files in src are included
# To build the regular float:    build_src_filter = -<*> +<float_main.c>
# To build the test reflashed:   build_src_filter = -<*> +<test_reflashed_main.c>
build_src_filter = -<*> +<surface_main.c>

monitor_filters = colorize, send_on_enter
monitor_echo = yes