[env:adafruit_feather]
# We use the community fork that allows Pico SDK on non-Pico boards
platform = raspberrypi
board = adafruit_feather
framework = picosdk

# Optimization and Serial Monitor
monitor_speed = 115200
build_type = debug

build_flags =
    -O2
    -D PICO_STDIO_USB=1
    -D PICO_USB=1
    ; Add include paths for your libraries so main.c can find the .h files
    -I lib/MS5837
    ; -I lib/Other_Library

# Just like your other project, ensure all files in src are included
build_src_filter = +<*>

lib_deps = 
    MS5837