[env:adafruit_feather]
# We use the community fork that allows Pico SDK on non-Pico boards
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = picosdk

# Optimization and Serial Monitor
monitor_speed = 115200
build_type = debug
build_unflags = -D PICO_STDIO_UART
build_flags =
    -O2
    -D PICO_STDIO_USB
    -D PICO_USB=1
    ; Add include paths for your libraries so main.c can find the .h files
    -I lib/MS5837
    ; -I lib/Other_Library
    -Wl,-u,_printf_float
    -D PICO_STDIO_UART=0
    -Wl,-u,_scanf_float
    -I lib/BN085
    -I lib/RadioLib

# Just like your other project, ensure all files in src are included
build_src_filter = build_src_filter = -<*> +<float_main.c>

lib_deps = 
    MS5837
    BN085
    RadioLib

monitor_filters = colorize, send_on_enter
monitor_echo = yes